/**
 * Curated, primitive-free example programs for the Haskell panel (ADR 0007, §B3).
 *
 * Each carries the Haskell-ish `source` shown in the editor and the
 * `-ddump-combinator` `dump` it compiles to. Until the MicroHs→WASM blob lands
 * (Phase 0), the stub compiler keys off the source text to return the matching
 * canned dump, so the whole pipeline (dump → tree → spawn) runs end-to-end now.
 *
 * The dumps were generated by bracket-abstracting the lambda forms and verified
 * by reducing them through the core (`dumpToTree` + `normalize`); the reduced
 * normal form is noted beside each.
 */

/** A bundled example: editor source plus its canned combinator dump. */
export interface Example {
  /** Short menu label. */
  name: string;
  /** Haskell-ish source shown in the editor. */
  source: string;
  /** The `-ddump-combinator` text this source compiles to. */
  dump: string;
  /** Optional root definition to inline from (defaults to the last def). */
  root?: string;
  /** One-line description shown under the menu. */
  note: string;
}

export const EXAMPLES: Example[] = [
  {
    name: "Scott booleans",
    note: "and True (not True)  →  False",
    source: `-- Scott-encoded booleans (no primitives).
data Bool = True | False

not :: Bool -> Bool
not b = b False True

and :: Bool -> Bool -> Bool
and p q = p q False

test :: Bool
test = and True (not True)`,
    dump: `Main.true = K
Main.false = (K I)
Main.not = ((S ((S I) (K (K I)))) (K K))
Main.and = ((S S) (K (K (K I))))
Main.test = Main.and Main.true (Main.not Main.true)`,
  },
  {
    name: "Scott pairs",
    note: "fst (I, snd (I, I))  →  I",
    source: `-- Scott-encoded pairs: a value applies the eliminator to its fields.
pair x y = \\s -> s x y
fst p = p (\\x y -> x)
snd p = p (\\x y -> y)

test = fst (pair I (snd (pair I I)))`,
    dump: `Main.pair = ((S ((S (K S)) ((S (K K)) ((S (K S)) ((S (K (S I))) K))))) (K K))
Main.fst = ((S I) (K K))
Main.snd = ((S I) (K (K I)))
Main.test = Main.fst (Main.pair I (Main.snd (Main.pair I I)))`,
  },
  {
    name: "Combinator birds",
    note: "B (Bluebird) ∘ C (Cardinal)  →  S",
    source: `-- Straight combinator algebra: compose (B) and flip (C).
comp = \\f g x -> f (g x)   -- the Bluebird B
flip = \\f x y -> f y x      -- the Cardinal C

test = comp flip K I S I`,
    dump: `Main.flip = C
Main.comp = B
Main.test = Main.comp Main.flip K I S I`,
  },
  {
    name: "Reject: IO",
    note: "no ι form — IO/FFI has no combinator tree",
    source: `-- IO has no combinatory form: this is rejected on purpose.
greeting :: String
greeting = "hello, world"

main :: IO ()
main = putStrLn greeting`,
    dump: `Main.greeting = "hello, world"
Main.main = IO.putStrLn Main.greeting`,
    root: "Main.main",
  },
];
