/**
 * Live MicroHs compile worker (ADR 0007): host the vendored **batch** MicroHs blob
 * (`/vendor/mhs/mhs-batch.js`, built by `nix/build-wasm.sh`) and compile one
 * program to a `-ddump-combinator` dump, headless.
 *
 * A *classic* worker — the Emscripten blob loads via `importScripts` and detects
 * `ENVIRONMENT_IS_WORKER`. We run `main` the Emscripten way: set `Module.arguments`,
 * write the source into the MEMFS in `preRun`, override `print` to capture stdout,
 * and let the runtime auto-run (`callMain` re-enters and blows the JS stack). The
 * dump is reported from `postRun`/`onExit` — the batch blob links EXIT_RUNTIME so
 * stdout actually flushes (the stock interactive blob didn't).
 *
 * Base is embedded in the blob's FS at `/lib` (the GHC build can't serialize a
 * .pkg), so we compile with `-i. -i/lib`. To avoid recompiling the Prelude every
 * time (~65s → ~30s), the caller passes a **prewarmed module cache** (`base.mhscache`,
 * generated by `scripts/gen-mhs-cache.mjs` — only the blob's eval runtime can write
 * it) in the message; we write it and read it with `-CR`. (Fetching it here, in an
 * async `onmessage`, broke the run — keep `onmessage` synchronous.) If there's no
 * cache we compile cold. A trailing stderr "No definition found for: Ex.main" is the
 * harmless post-dump link error. One compile per worker — `compiler.ts` terminates us.
 */
/// <reference lib="webworker" />
declare function importScripts(...urls: string[]): void;

const post = (msg: { dump?: string; error?: string }): void => (self as unknown as Worker).postMessage(msg);

self.onmessage = (e: MessageEvent<{ source: string; cache: ArrayBuffer | null }>): void => {
  const source = e.data.source;
  const cache = e.data.cache ? new Uint8Array(e.data.cache) : null; // prewarmed Prelude cache (halves compile time)
  let captured = "";
  let errText = "";
  let done = false;
  const finish = (): void => {
    if (done) return;
    done = true;
    // The dump is present iff a definition line (` = `) was printed; the trailing
    // "No definition found for: Ex.main" link error is expected and ignored.
    if (captured.includes(" = ")) post({ dump: captured });
    else post({ error: (errText.trim() || captured.trim() || "the compiler produced no combinators").split("\n").slice(-1)[0] });
  };

  (self as unknown as { Module: unknown }).Module = {
    arguments: cache
      ? ["-CR", "-ddump-combinator", "-i.", "-i/lib", "Ex"]
      : ["-ddump-combinator", "-i.", "-i/lib", "Ex"],
    print: (t: string) => {
      captured += t + "\n";
    },
    printErr: (t: string) => {
      errText += t + "\n";
    },
    preRun: [
      function (this: { FS: { writeFile(p: string, d: string | Uint8Array): void } }) {
        if (cache) this.FS.writeFile("/.mhscache", cache); // read with -CR
        this.FS.writeFile("Ex.hs", source); // CWD is /, found by -i.
      },
    ],
    postRun: [finish],
    onExit: finish,
    onAbort: (x: unknown) => {
      if (done) return;
      done = true;
      post({ error: `compiler aborted: ${errText.trim() || String(x)}` });
    },
  };

  try {
    importScripts("/vendor/mhs/mhs-batch.js");
  } catch (err) {
    if (!done) {
      done = true;
      post({ error: `couldn't load the MicroHs blob — build it with nix/build-wasm.sh (${(err as Error).message})` });
    }
  }
};
