/**
 * Generate the egg rewrite table (`crates/refold/src/rules.txt`) from the
 * combinator catalogue — the single source of truth — so the Rust re-sugarer
 * and the TypeScript core never drift.
 *
 * Each output line is `name | lhs | rhs`, a sound equation in egg s-expression
 * syntax (`@` = application, bare atoms = leaves, `?x` = pattern variable). Rust
 * decides per-line which direction(s) are valid e-match rules. We emit, per law:
 *   - its behavioural equation  `sym v… = reference(v…)`  (skipped for laws that
 *     are only finitely *probeable*, i.e. recursive Y), and
 *   - its definitional equation `<SKI tree of def> = sym`  (for birds with a def).
 * Plus the one rule the catalogue has no entry for: ι's unfolding `ι x = x S K`.
 *
 * Run with:  npx tsx scripts/gen-rules.ts
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { CATALOG } from "../src/core/catalog";
import { type Node, app, comb, freeVar } from "../src/core/term";

const VAR_NAMES = ["a", "b", "c", "d", "e", "f"]; // mirrors probe.ts

// Catalog symbols that are not valid bare s-expression atoms (they contain
// parens, or are non-ASCII) get an egg-safe alias; everything else is itself.
const TOKEN: Record<string, string> = {
  "(+)": "add",
  "(-)": "sub",
  "<>": "append",
  "Φ": "Phi",
  "Ψ": "Psi",
};
const tok = (sym: string): string => TOKEN[sym] ?? sym;

/** Serialize a term to egg s-expression syntax (free vars → pattern variables). */
function egg(n: Node): string {
  switch (n.kind) {
    case "iota":
      return "iota";
    case "free":
      return `?${n.name}`;
    case "comb":
      return tok(n.sym);
    case "app":
      return `(@ ${egg(n.fn)} ${egg(n.arg)})`;
  }
}

const lines: string[] = [
  "# Generated by scripts/gen-rules.ts from src/core/catalog.ts — do not edit.",
  "# Format: name | lhs | rhs  (a sound equation; Rust picks valid directions).",
  "",
  "# ι unfolding (not a catalog law).",
  `iota | (@ iota ?a) | (@ (@ ?a S) K)`,
  "",
];

for (const law of CATALOG) {
  const name = tok(law.sym);
  // Behavioural law: sym applied to fresh vars equals its reference output.
  // Skip laws supplying custom probe args (only Y, whose true law is recursive
  // and unsound as a rewrite); Y is still recovered via its definitional eq.
  if (!law.args) {
    const vars = VAR_NAMES.slice(0, law.arity).map(freeVar);
    const lhs = vars.reduce<Node>((acc, v) => app(acc, v), comb(law.sym));
    const rhs = law.reference(vars);
    lines.push(`${name}_law | ${egg(lhs)} | ${egg(rhs)}`);
  }
  // Definitional law: the bird's underlying SKI tree equals its name.
  if (law.def) {
    lines.push(`${name}_def | ${egg(law.def())} | ${tok(law.sym)}`);
  }
}

const here = dirname(fileURLToPath(import.meta.url));
const out = resolve(here, "../crates/refold/src/rules.txt");
writeFileSync(out, lines.join("\n") + "\n");
console.log(`wrote ${lines.filter((l) => l && !l.startsWith("#")).length} rule lines → ${out}`);
